import Image from "next/image";
import Link from "next/link";
import type { DriverListItem } from "@/features/drivers/types/driver";
import type { Order } from "@/features/orders/types/order";
import type { AdminUserLookup } from "@/services/shipments-api";

export default function OrderDetailsPanel({ order, recipient, driver, t }: { order: Order; recipient: AdminUserLookup | null; driver: DriverListItem | null; t: (key: string, values?: Record<string, string | number>) => string }) {
  const recipientName = recipient?.name ?? t("recipientUnavailable");
  const driverName = driver?.name ?? (order.driverId ? t("driverUnavailable") : t("noDriverAssigned"));

  return <section className="rounded-2xl border border-border/40 bg-card p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] text-text-secondary">{t("orderDetails")}</p><h2 className="mt-1 text-lg font-semibold">{order.orderNumber}</h2></div><span className="rounded-full bg-primary-muted px-3 py-1 text-[10px] font-medium text-primary">{t(`status.${order.status}`)}</span></div><dl className="mt-6 grid grid-cols-2 gap-4 text-xs"><div><dt className="text-[10px] text-text-secondary">{t("recipient")}</dt><dd className="mt-1 font-medium">{recipient ? <Link href={`/users/${recipient.id}`} className="text-text-primary underline decoration-transparent underline-offset-2 transition hover:text-primary hover:decoration-primary focus-visible:rounded-sm focus-visible:outline-2 focus-visible:outline-primary">{recipientName}</Link> : recipientName}{recipient?.phoneNumber && <span className="mt-1 block text-[10px] text-text-secondary">{recipient.phoneNumber}</span>}</dd></div><div><dt className="text-[10px] text-text-secondary">{t("driver")}</dt><dd className="mt-1 font-medium">{driverName}</dd></div><div><dt className="text-[10px] text-text-secondary">{t("pickup")}</dt><dd className="mt-1">{order.pickupAddress}</dd></div><div><dt className="text-[10px] text-text-secondary">{t("delivery")}</dt><dd className="mt-1">{order.deliveryAddress}</dd></div></dl><div className="mt-6 border-t border-border/40 pt-4 text-xs"><div className="flex justify-between py-1"><span className="text-text-secondary">{t("baseFee")}</span><span>—</span></div><div className="flex justify-between py-1"><span className="text-text-secondary">{t("tax")}</span><span>—</span></div><div className="mt-2 flex justify-between border-t border-border/40 pt-3 font-semibold"><span>{t("totalFee")}</span><span className="text-primary">{order.price}</span></div></div><div className="mt-5 rounded-xl bg-secondary p-3 text-xs"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] text-text-secondary">{t("driverDetails")}</p><p className="mt-1 font-medium">{driverName}</p><p className="mt-1 text-text-secondary">{driver ? `${driver.vehicleBrand} · ${driver.vehicleType} · ${driver.plateNumber}` : "—"}</p></div>{driver && <Image src="/image%20296.png" alt="" width={104} height={64} className="h-16 w-24 rounded-lg object-contain" />}</div></div></section>;
}
